name: php-package-template
services:
  appserver:
    type: php:custom
    via: cli
    overrides:
      image: slimdeluxe/php:8.3-v1.0
tooling:
  php:
    service: appserver
  composer:
    service: appserver
  test:
    service: appserver
    description: Run tests
    cmd: "composer test"
  format:
    service: appserver
    description: Fix code style issues
    cmd: "composer format"
